#!/usr/bin/env python3
"""Manage user-scoped agent skills, agent files, and plugins.

Locally-authored skills live unprefixed under skills/. Remote skills are
cloned into .vendor/ from the sources declared in config.yaml. Both are
rendered into .build/skills/<owner>-<name>/ with a frontmatter `name` that
matches the directory, per the Agent Skills spec (agentskills.io), and then
symlinked into the per-tool targets declared in config.yaml.

Usage:
    ./agents.py sync            fetch + build + link (the everyday command)
    ./agents.py fetch           clone/update remote sources only
    ./agents.py build           render .build/ only
    ./agents.py link            refresh symlinks only
    ./agents.py status          show what is installed and where it came from
    ./agents.py list            list every resolvable skill
    ./agents.py unlink          remove every symlink this repo owns
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from typing import NoReturn
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent
VENDOR = REPO / ".vendor"
BUILD = REPO / ".build"
SKILL_FILE = "SKILL.md"
# Kinds a tool may declare a target for.
DIR_KINDS = ("skills", "subagents", "plugins")
FILE_KINDS = ("config",)
# `rules` takes a directory of themed files, optionally merged into one.
DUAL_KINDS = ("rules",)
KINDS = DIR_KINDS + FILE_KINDS + DUAL_KINDS
MERGED_RULES = "AGENTS.md"
RULES_BANNER = (
    "<!-- Generated by agents.py from rules/*.md — do not edit here. -->"
)
FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---[ \t]*\r?\n?", re.DOTALL)
NAME_LINE = re.compile(r"^name:.*$", re.MULTILINE)


# --------------------------------------------------------------------------
# output


class Out:
    quiet = False
    json = False
    warnings: list[str] = []

    @staticmethod
    def say(msg: str) -> None:
        if not (Out.quiet or Out.json):
            print(msg)

    @staticmethod
    def warn(msg: str) -> None:
        Out.warnings.append(msg)
        if not Out.json:
            print(f"warning: {msg}", file=sys.stderr)

    @staticmethod
    def die(msg: str) -> NoReturn:
        if Out.json:
            print(json.dumps({"ok": False, "error": msg}, indent=2))
            sys.exit(1)
        sys.exit(f"error: {msg}")


# --------------------------------------------------------------------------
# config


def split_git_url(url: str) -> list[str]:
    """Break a git URL into its path segments, host first.

    Handles the three shapes git accepts:
        https://github.com/org/repo.git  -> [github.com, org, repo]
        git@github.com:org/repo.git      -> [github.com, org, repo]
        ssh://git@github.com/org/repo    -> [github.com, org, repo]
    """
    body = url.strip()
    for prefix in ("https://", "http://", "ssh://", "git+ssh://"):
        body = body.removeprefix(prefix)
    body = body.split("@", 1)[-1]  # drop any user@ portion
    body = body.replace(":", "/").removesuffix(".git")
    return [p for p in body.split("/") if p and p not in (".", "..")]


@dataclass
class Source:
    owner: str
    repo: str
    ref: str | None = None
    # Subdirectories to scan. An entry reading "not <path>" excludes instead.
    paths: list[str] = field(default_factory=list)

    @property
    def url(self) -> str:
        if "://" in self.repo or self.repo.startswith("git@"):
            return self.repo
        return f"https://github.com/{self.repo}.git"

    @property
    def slug(self) -> str:
        """Filesystem-safe identity for this source inside .vendor/."""
        return "/".join(split_git_url(self.url))

    @property
    def checkout(self) -> Path:
        return VENDOR / self.slug

    @property
    def includes(self) -> list[str]:
        """Subdirectories to scan; the repo root when none are given."""
        return [p for p in self.paths if not is_negated(p)] or [""]

    @property
    def excludes(self) -> list[str]:
        return [p.split(None, 1)[1].strip("/") for p in self.paths if is_negated(p)]

    def wants(self, relative: str) -> bool:
        """Whether a skill at `relative` (posix, from the checkout) is kept."""
        return not any(path_matches(relative, pat) for pat in self.excludes)


def is_negated(entry: str) -> bool:
    """True for a path written as `not <path>`."""
    head, _, rest = entry.partition(" ")
    return head == "not" and bool(rest.strip())


def path_matches(relative: str, pattern: str) -> bool:
    """True if `relative`, or any directory above it, matches `pattern`.

    So "skills/deprecated" excludes everything beneath it, and a glob like
    "skills/*.archived" excludes each directory it matches.
    """
    if relative == pattern or relative.startswith(f"{pattern}/"):
        return True
    parts = relative.split("/")
    return any(
        fnmatch.fnmatch("/".join(parts[:i]), pattern)
        for i in range(1, len(parts) + 1)
    )


@dataclass
class Target:
    """Where one kind of artefact is installed, and how.

    `merge` applies to `rules` only: false links each themed file, true
    concatenates them into a single generated file.
    """

    path: Path
    merge: bool = False

    @property
    def is_file(self) -> bool:
        """True when the path names a file rather than a directory."""
        return self.path.suffix == ".md"

    @property
    def merged_path(self) -> Path:
        """Where the concatenated file lands when merging."""
        return self.path if self.is_file else self.path / MERGED_RULES


@dataclass
class Config:
    owner: str
    owner_from: str  # how `owner` was resolved, for `status`
    targets: dict[str, dict[str, Target]]  # tool -> kind -> target
    sources: list[Source]


def expand(raw: str) -> Path:
    return Path(os.path.expandvars(str(raw))).expanduser()


def derive_owner(remote: str) -> tuple[str, str]:
    """Infer the owner prefix from this repo's own git remote.

    Returns (owner, explanation). Exits with guidance if it cannot be found,
    because guessing here would rename every skill you author.
    """
    hint = (
        f"Set `owner:` explicitly in config.yaml, or add the remote:\n"
        f"    git remote add {remote} git@github.com:<org>/<repo>.git"
    )
    try:
        url = git("remote", "get-url", remote, cwd=REPO)
    except RuntimeError:
        Out.die(f"owner is `auto` but this repo has no '{remote}' remote.\n{hint}")

    parts = split_git_url(url)
    if len(parts) < 3:
        Out.die(f"owner is `auto` but could not parse an org from '{url}'.\n{hint}")
    return parts[-2], f"auto, from {remote} ({url})"


CONFIG_FILE = "config.yaml"
LOCAL_CONFIG_FILE = "config.local.yaml"
RETIRED = ("agents.yaml", "skills.yaml", "skills.local.yaml")


BANG_NEGATION = re.compile(r"^\s*-\s+!+\s*(?P<path>\S.*?)\s*$", re.MULTILINE)


def check_bang_negation(filename: str, text: str) -> None:
    """Reject `- ! path`, which YAML would quietly turn into an inclusion.

    A leading `!` is a YAML tag. Followed by a space the tag is
    non-specific and is discarded, so `- ! skills/deprecated` parses as
    plain `skills/deprecated` — an exclusion inverted into an inclusion,
    with nothing to notice at runtime. Without the space it is a hard parse
    error. Negation is written `not <path>` here for exactly this reason.
    """
    for match in BANG_NEGATION.finditer(text):
        found = match.group("path").strip("'\"")
        Out.die(
            f"{filename}: `- ! {found}` is not how exclusions are written, and "
            f"YAML would drop the `!` and include the path instead. Use:\n"
            f"    - not {found}"
        )


def load_config() -> Config:
    main = REPO / CONFIG_FILE
    if not main.exists():
        stale = [f for f in RETIRED if (REPO / f).exists()]
        hint = (
            f"\nFound {', '.join(stale)}: these merged into {CONFIG_FILE}."
            if stale
            else ""
        )
        Out.die(f"missing {main}{hint}")

    # config.local.yaml is gitignored: somewhere to keep private or
    # work-internal settings without publishing them. Scalar keys override,
    # `sources` accumulate.
    layers: list[tuple[str, dict]] = []
    for path in (main, REPO / LOCAL_CONFIG_FILE):
        if path.exists():
            text = path.read_text()
            check_bang_negation(path.name, text)
            layers.append((path.name, yaml.safe_load(text) or {}))

    data: dict = {}
    for _, layer in layers:
        data.update(layer)

    raw_owner = data.get("owner")
    if raw_owner is None or str(raw_owner).strip().lower() in ("auto", ""):
        owner, owner_from = derive_owner(str(data.get("owner_remote") or "origin"))
    else:
        owner, owner_from = str(raw_owner).strip(), CONFIG_FILE

    targets: dict[str, dict[str, Target]] = {}
    raw_targets = data.get("targets") or {}
    if any(not isinstance(v, dict) for v in raw_targets.values()):
        Out.die(
            "targets must be grouped by tool, e.g.\n"
            "    targets:\n"
            "      opencode:\n"
            "        skills: ~/.config/opencode/skill"
        )
    for tool, kinds in raw_targets.items():
        parsed: dict[str, Target] = {}
        for kind, value in kinds.items():
            where = f"{CONFIG_FILE}: `{tool}.{kind}`"
            if kind == "agents":
                Out.die(
                    f"{where} was renamed to `subagents`, and the directory it "
                    f"installs from is now subagents/.\nRename the key; the path "
                    f"it points at does not change."
                )
            if kind not in KINDS:
                Out.die(
                    f"{where} is not a recognised target. "
                    f"Expected one of: {', '.join(KINDS)}"
                )
            # A bare string is shorthand for `path`.
            if not isinstance(value, dict):
                parsed[kind] = Target(path=expand(value))
                continue

            unknown = set(value) - {"path", "merge"}
            if unknown:
                Out.die(f"{where} has unknown key(s): {', '.join(sorted(unknown))}")
            if not value.get("path"):
                Out.die(f"{where} needs a `path`")
            if "merge" in value and kind not in DUAL_KINDS:
                Out.die(f"{where} does not support `merge`")
            parsed[kind] = Target(
                path=expand(value["path"]), merge=bool(value.get("merge", False))
            )

        rules = parsed.get("rules")
        if rules and rules.is_file and not rules.merge:
            Out.die(
                f"{CONFIG_FILE}: `{tool}.rules.path` names a file "
                f"({rules.path.name}) but `merge` is false, so there are many "
                f"files to install and one place to put them.\n"
                f"Set `merge: true`, or point `path` at a directory."
            )
        targets[str(tool)] = parsed
    if not targets:
        Out.die(f"{CONFIG_FILE} must declare at least one tool under `targets`")

    sources = []
    for name, layer in layers:
        for i, entry in enumerate(layer.get("sources") or []):
            where = f"{name} source #{i + 1}"
            src_repo = entry.get("repo")
            if not src_repo:
                Out.die(f"{where} needs a `repo`")

            # Default the prefix to the org the repo belongs to, so
            # mattpocock/skills yields "mattpocock".
            src_owner = entry.get("owner")
            if not src_owner:
                parts = split_git_url(Source(owner="", repo=str(src_repo)).url)
                if len(parts) < 3:
                    Out.die(
                        f"{where}: could not read an owner from "
                        f"'{src_repo}'. Set `owner` explicitly."
                    )
                src_owner = parts[-2]

            retired = {"include", "exclude"} & set(entry)
            if retired:
                Out.die(
                    f"{where} uses `{'`, `'.join(sorted(retired))}`, which "
                    f"`path` replaced. Select by location instead:\n"
                    f"    path:\n"
                    f"      - skills\n"
                    f"      - not skills/deprecated"
                )

            raw = entry.get("path") or []
            paths = [raw] if isinstance(raw, str) else list(raw)
            sources.append(
                Source(
                    owner=str(src_owner),
                    repo=str(src_repo),
                    ref=entry.get("ref"),
                    paths=[str(p).strip().strip("/") for p in paths if str(p).strip()],
                )
            )
    return Config(
        owner=owner, owner_from=owner_from, targets=targets, sources=sources
    )


# --------------------------------------------------------------------------
# discovery


@dataclass
class Skill:
    owner: str
    name: str  # unprefixed, as found on disk
    src: Path  # directory containing SKILL.md
    origin: str  # "local" or the source repo slug

    @property
    def full(self) -> str:
        return f"{self.owner}-{self.name}"


def find_skills(root: Path, owner: str, origin: str) -> list[Skill]:
    """Recursively collect every directory holding a SKILL.md."""
    if not root.is_dir():
        return []
    found = []
    for skill_md in sorted(root.rglob(SKILL_FILE)):
        d = skill_md.parent
        if any(part.startswith(".") for part in d.relative_to(root).parts):
            continue
        found.append(Skill(owner=owner, name=d.name, src=d, origin=origin))
    return found


def collect(cfg: Config, *, require_fetch: bool = True) -> list[Skill]:
    skills = find_skills(REPO / "skills", cfg.owner, "local")

    for source in cfg.sources:
        if not source.checkout.exists():
            if require_fetch:
                Out.warn(
                    f"{source.slug} not fetched yet; run `./agents.py fetch`"
                )
            continue

        for include in source.includes:
            root = source.checkout / include if include else source.checkout
            if not root.is_dir():
                Out.warn(f"{source.slug}: path '{include}' does not exist")
                continue
            for skill in find_skills(root, source.owner, source.slug):
                relative = skill.src.relative_to(source.checkout).as_posix()
                if source.wants(relative):
                    skills.append(skill)

    seen: dict[str, Skill] = {}
    for skill in skills:
        if skill.full in seen:
            if skill.src != seen[skill.full].src:
                Out.warn(
                    f"duplicate skill '{skill.full}' from {skill.origin}; "
                    f"keeping the one from {seen[skill.full].origin}"
                )
            continue
        seen[skill.full] = skill
    return sorted(seen.values(), key=lambda s: s.full)


# --------------------------------------------------------------------------
# fetch


def git(*args: str, cwd: Path | None = None) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError((result.stderr or result.stdout).strip())
    return result.stdout.strip()


def fetch(cfg: Config) -> list[dict]:
    fetched: list[dict] = []
    if not cfg.sources:
        Out.say("no remote sources declared in config.yaml")
        return fetched
    for source in cfg.sources:
        dest = source.checkout
        action = "updated" if dest.exists() else "cloned"
        try:
            if dest.exists():
                Out.say(f"updating {source.slug}")
                git("fetch", "--tags", "--prune", "origin", cwd=dest)
            else:
                Out.say(f"cloning {source.slug}")
                dest.parent.mkdir(parents=True, exist_ok=True)
                git("clone", "--quiet", source.url, str(dest))

            ref = source.ref or git(
                "rev-parse", "--abbrev-ref", "origin/HEAD", cwd=dest
            ).split("/")[-1]
            # Prefer the remote-tracking branch so updates actually land.
            target = ref
            try:
                git("rev-parse", "--verify", f"origin/{ref}", cwd=dest)
                target = f"origin/{ref}"
            except RuntimeError:
                pass
            git("checkout", "--quiet", "--detach", target, cwd=dest)
            revision = git("rev-parse", "--short", "HEAD", cwd=dest)
            Out.say(f"  {source.slug} @ {revision}")
            fetched.append(
                {
                    "source": source.slug,
                    "owner": source.owner,
                    "action": action,
                    "revision": revision,
                }
            )
        except RuntimeError as exc:
            Out.warn(f"{source.slug}: {exc}")
            fetched.append(
                {
                    "source": source.slug,
                    "owner": source.owner,
                    "action": "failed",
                    "error": str(exc),
                }
            )
    return fetched


# --------------------------------------------------------------------------
# build


def render_skill_md(text: str, full_name: str, skill: Skill) -> str:
    """Return SKILL.md with its frontmatter `name` forced to full_name."""
    match = FRONTMATTER.match(text)
    if not match:
        Out.warn(f"{skill.origin}/{skill.name}: no YAML frontmatter; copying as-is")
        return text

    block, body = match.group(1), text[match.end() :]
    if NAME_LINE.search(block):
        block = NAME_LINE.sub(f"name: {full_name}", block, count=1)
    else:
        block = f"name: {full_name}\n{block}"
    return f"---\n{block}\n---\n{body}"


def build(cfg: Config, skills: list[Skill]) -> Path:
    out = BUILD / "skills"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    for skill in skills:
        dest = out / skill.full
        dest.mkdir()
        for entry in sorted(skill.src.iterdir()):
            if entry.name == SKILL_FILE:
                continue
            # Symlink everything else so edits in the source are live.
            (dest / entry.name).symlink_to(entry.resolve())
        text = (skill.src / SKILL_FILE).read_text(encoding="utf-8")
        (dest / SKILL_FILE).write_text(
            render_skill_md(text, skill.full, skill), encoding="utf-8"
        )
    Out.say(f"built {len(skills)} skill(s) into {out.relative_to(REPO)}")
    return out


# --------------------------------------------------------------------------
# link


def owned_by_repo(link: Path) -> bool:
    """True if `link` is a symlink pointing somewhere inside this repo."""
    if not link.is_symlink():
        return False
    target = Path(os.path.realpath(link))
    return target == REPO or REPO in target.parents


def relink(target_dir: Path, wanted: dict[str, Path]) -> dict[str, list[str]]:
    """Make target_dir contain exactly `wanted` among repo-owned symlinks."""
    target_dir.mkdir(parents=True, exist_ok=True)
    added: list[str] = []
    removed: list[str] = []

    for existing in sorted(target_dir.iterdir()):
        if owned_by_repo(existing) and existing.name not in wanted:
            existing.unlink()
            removed.append(existing.name)
            Out.say(f"  - {existing.name}")

    for name, src in sorted(wanted.items()):
        link = target_dir / name
        src = src.resolve()
        if link.is_symlink():
            if Path(os.path.realpath(link)) == src:
                continue
            if not owned_by_repo(link):
                Out.warn(f"{link} is a foreign symlink; leaving it alone")
                continue
            link.unlink()
        elif link.exists():
            Out.warn(f"{link} exists and is not a symlink; leaving it alone")
            continue
        link.symlink_to(src)
        added.append(name)
        Out.say(f"  + {name}")

    return {"added": added, "removed": removed}


def link_file(link: Path, src: Path | None) -> dict[str, list[str]]:
    """Point a single path at `src`, or remove it when `src` is None.

    Used for targets that are one file rather than a directory of entries,
    like opencode's global ~/.config/opencode/AGENTS.md.
    """
    if src is None or not src.exists():
        if owned_by_repo(link):
            link.unlink()
            Out.say(f"  - {link.name}")
            return {"added": [], "removed": [link.name]}
        return {"added": [], "removed": []}

    src = src.resolve()
    if link.is_symlink():
        if Path(os.path.realpath(link)) == src:
            return {"added": [], "removed": []}
        if not owned_by_repo(link):
            Out.warn(f"{link} is a foreign symlink; leaving it alone")
            return {"added": [], "removed": []}
        link.unlink()
    elif link.exists():
        Out.warn(f"{link} exists and is not a symlink; leaving it alone")
        return {"added": [], "removed": []}

    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(src)
    Out.say(f"  + {link.name}")
    return {"added": [link.name], "removed": []}


def rule_files() -> list[Path]:
    """Themed rule files, in the order they are merged.

    An AGENTS.md here is the primary file, so it leads; the themed files
    follow alphabetically, which numeric prefixes can reorder.
    """
    src = REPO / "rules"
    if not src.is_dir():
        return []
    files = [f for f in sorted(src.glob("*.md")) if f.name != "README.md"]
    return sorted(files, key=lambda f: (f.name != MERGED_RULES, f.name))


def render_rules() -> Path | None:
    """Concatenate rules/*.md into one file, for `merge: true` targets.

    Each section is labelled with its source; Claude Code strips block-level
    HTML comments before loading, so the labels cost no context there.
    """
    out_dir = BUILD / "rules"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / MERGED_RULES

    files = rule_files()
    if not files:
        out.unlink(missing_ok=True)
        return None

    parts = [RULES_BANNER]
    for f in files:
        parts.append(f"<!-- {f.relative_to(REPO)} -->\n\n{f.read_text().strip()}")
    out.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    return out


def dir_entries(kind: str, built: Path) -> dict[str, Path]:
    """The set of entries a directory target of `kind` should contain."""
    if kind == "skills":
        return {d.name: d for d in sorted(built.iterdir()) if d.is_dir()}

    # subagents/, plugins/ and rules/ are named for their kind.
    src = REPO / kind
    if not src.is_dir():
        return {}
    markdown_only = kind in ("subagents", "rules")
    entries = sorted(src.glob("*.md")) if markdown_only else sorted(src.iterdir())
    # README.md documents the directory and examples/ demonstrates it;
    # neither is an artefact to install.
    return {
        f.name: f
        for f in entries
        if not f.name.startswith(".") and f.name not in ("README.md", "examples")
    }


def file_source(tool: str, kind: str, target: Path) -> Path:
    """The repo file a single-file target should point at.

    `config` is per-tool, read from settings/<tool>/ — tool config filenames
    are generic enough to collide (settings.json, config.toml) so they are
    kept in separate directories.
    """
    return REPO / "settings" / tool / target.name


def prune_stale_targets(cfg: Config) -> list[str]:
    """Clean up targets this repo linked before but no longer declares.

    Retargeting — including switching `rules` between a directory and a
    concatenated file — would otherwise leave the old location populated. For
    rules that is not merely untidy: the old directory would still be globbed
    and every rule would load twice.
    """
    record = BUILD / "linked.json"
    current = {str(t.path) for kinds in cfg.targets.values() for t in kinds.values()}

    previous: set[str] = set()
    if record.exists():
        try:
            previous = set(json.loads(record.read_text()))
        except (json.JSONDecodeError, TypeError):
            pass

    pruned: list[str] = []
    for stale in sorted(previous - current):
        path = Path(stale)
        if owned_by_repo(path):
            path.unlink()
            pruned.append(str(path))
            Out.say(f"  - {path} (no longer a target)")
        elif path.is_dir():
            for entry in sorted(path.iterdir()):
                if owned_by_repo(entry):
                    entry.unlink()
                    pruned.append(str(entry))
                    Out.say(f"  - {entry} (no longer a target)")
            if not any(path.iterdir()):
                path.rmdir()

    record.parent.mkdir(parents=True, exist_ok=True)
    record.write_text(json.dumps(sorted(current), indent=2) + "\n")
    return pruned


def link(cfg: Config, built: Path) -> dict:
    result: dict = {"pruned": prune_stale_targets(cfg), "targets": []}
    for tool, kinds in cfg.targets.items():
        for kind, target in kinds.items():
            Out.say(f"linking {tool}.{kind} -> {target.path}")
            if kind == "rules" and target.merge:
                merged = render_rules()
                if target.is_file:
                    changed = link_file(target.path, merged)
                else:
                    # Through relink, so any per-file symlinks left by a
                    # previous merge: false are cleared from the directory.
                    changed = relink(
                        target.path, {MERGED_RULES: merged} if merged else {}
                    )
            elif kind in FILE_KINDS:
                changed = link_file(target.path, file_source(tool, kind, target.path))
            else:
                changed = relink(target.path, dir_entries(kind, built))
            result["targets"].append(
                {"tool": tool, "kind": kind, "path": str(target.path), **changed}
            )
        check_rules_wiring(tool, kinds)
    return result


# Tools that do not read a rules directory on their own and need to be
# pointed at it from their config. Claude Code reads ~/.claude/rules/
# natively, so it is absent here.
NEEDS_RULES_WIRING = {"opencode": "instructions"}


def check_rules_wiring(tool: str, kinds: dict[str, Target]) -> None:
    """Warn when linked rules are not actually loaded.

    opencode only reads a rules *directory* if its config globs it. That
    config is gitignored, so a fresh clone can end up with rules linked but
    silently never loaded — the one failure this target cannot detect itself.

    Merging into a directory still needs the glob: opencode reads AGENTS.md
    natively only at the top of its config directory, not inside a subfolder.
    """
    key = NEEDS_RULES_WIRING.get(tool)
    if key is None or "rules" not in kinds:
        return

    rules = kinds["rules"]
    if rules.is_file:
        return

    config = kinds.get("config")
    if config is None:
        Out.warn(
            f"{tool}: rules are linked to {rules.path} but {tool} has no "
            f"`config` target, so nothing can point `{key}` at them."
        )
        return

    source = file_source(tool, "config", config.path)
    if not source.exists():
        Out.warn(f"{tool}: {source} is missing; `{key}` cannot glob {rules.path}.")
        return

    # Match on the directory, so any glob shape inside it counts.
    home = str(Path.home())
    text = source.read_text(encoding="utf-8")
    needle = str(rules.path)
    if needle not in text and needle.replace(home, "~") not in text:
        Out.warn(
            f"{tool}: rules are linked to {rules.path} but {source.name} does "
            f"not glob them, so they will not load. Add to `{key}`:\n"
            f'    "{needle.replace(home, "~")}/*.md"'
        )


# --------------------------------------------------------------------------
# commands


def cmd_fetch(cfg: Config, _: argparse.Namespace) -> dict:
    return {"fetched": fetch(cfg)}


def cmd_build(cfg: Config, _: argparse.Namespace) -> dict:
    skills = collect(cfg)
    build(cfg, skills)
    return {"built": [s.full for s in skills]}


def cmd_link(cfg: Config, _: argparse.Namespace) -> dict:
    built = BUILD / "skills"
    if not built.is_dir():
        built = build(cfg, collect(cfg))
    return link(cfg, built)


def cmd_sync(cfg: Config, args: argparse.Namespace) -> dict:
    result: dict = {"fetched": [] if args.no_fetch else fetch(cfg)}
    skills = collect(cfg)
    result["built"] = [s.full for s in skills]
    result.update(link(cfg, build(cfg, skills)))
    Out.say("sync complete")
    return result


def cmd_list(cfg: Config, _: argparse.Namespace) -> dict:
    skills = collect(cfg, require_fetch=False)
    if not skills:
        Out.say("no skills found")
    elif not Out.json:
        width = max(len(s.full) for s in skills)
        for skill in skills:
            print(f"{skill.full:<{width}}  {skill.origin}")
    return {
        "skills": [
            {
                "name": s.full,
                "skill": s.name,
                "owner": s.owner,
                "origin": s.origin,
                "path": str(s.src),
            }
            for s in skills
        ]
    }


def target_state(
    kind: str, target: Target, skills: dict[str, Skill]
) -> tuple[str, list[dict]]:
    """What is currently installed at one target, and whether that is sound."""
    path = target.path
    if kind in FILE_KINDS or target.is_file:
        if owned_by_repo(path):
            return "linked", [
                {"name": path.name, "origin": "local", "broken": not path.exists()}
            ]
        return ("foreign" if path.exists() else "absent"), []

    if not path.is_dir():
        return "absent", []

    entries = []
    for entry in sorted(path.iterdir()):
        if not owned_by_repo(entry):
            continue
        origin = None
        if kind == "skills":
            skill = skills.get(entry.name)
            origin = skill.origin if skill else "STALE"
        entries.append(
            {"name": entry.name, "origin": origin, "broken": not entry.exists()}
        )
    return ("linked" if entries else "empty"), entries


def cmd_status(cfg: Config, _: argparse.Namespace) -> dict:
    skills = {s.full: s for s in collect(cfg, require_fetch=False)}

    sources = []
    for source in cfg.sources:
        revision = None
        if source.checkout.exists():
            try:
                revision = git("rev-parse", "--short", "HEAD", cwd=source.checkout)
            except RuntimeError:
                revision = "?"
        sources.append(
            {
                "source": source.slug,
                "owner": source.owner,
                "fetched": source.checkout.exists(),
                "revision": revision,
            }
        )

    targets = []
    for tool, kinds in cfg.targets.items():
        for kind, target in kinds.items():
            state, entries = target_state(kind, target, skills)
            targets.append(
                {
                    "tool": tool,
                    "kind": kind,
                    "path": str(target.path),
                    "merge": target.merge if kind == "rules" else None,
                    "state": state,
                    "entries": entries,
                }
            )

    result = {
        "repo": str(REPO),
        "owner": cfg.owner,
        "owner_from": cfg.owner_from,
        "sources": sources,
        "targets": targets,
    }
    if Out.json:
        return result

    print(f"repo   {REPO}")
    print(f"owner  {cfg.owner}  ({cfg.owner_from})")
    for item in sources:
        where = f"@ {item['revision']}" if item["fetched"] else "NOT FETCHED"
        print(f"source {item['source']} {where} (owner: {item['owner']})")

    for item in targets:
        note = "  (merged)" if item["merge"] else ""
        print(f"\n{item['tool']}.{item['kind']} -> {item['path']}{note}")
        if item["state"] == "absent":
            print("  (not linked)")
        elif item["state"] == "foreign":
            print("  (exists, but not linked from this repo)")
        elif item["state"] == "empty":
            print("  (nothing linked from this repo)")
        for entry in item["entries"]:
            origin = f"  <- {entry['origin']}" if entry["origin"] else ""
            broken = "  BROKEN" if entry["broken"] else ""
            print(f"  {entry['name']}{origin}{broken}")
    return result


def cmd_unlink(cfg: Config, _: argparse.Namespace) -> dict:
    removed: list[str] = []
    for tool, kinds in cfg.targets.items():
        for kind, target in kinds.items():
            path = target.path
            if kind in FILE_KINDS or target.is_file:
                if owned_by_repo(path):
                    Out.say(f"unlinking {tool}.{kind} from {path}")
                    path.unlink()
                    removed.append(str(path))
                    Out.say(f"  - {path.name}")
                continue
            if not path.is_dir():
                continue
            Out.say(f"unlinking {tool}.{kind} from {path}")
            for entry in sorted(path.iterdir()):
                if owned_by_repo(entry):
                    entry.unlink()
                    removed.append(str(entry))
                    Out.say(f"  - {entry.name}")
    Out.say(f"removed {len(removed)} symlink(s)")
    return {"removed": removed}


COMMANDS = {
    "sync": cmd_sync,
    "fetch": cmd_fetch,
    "build": cmd_build,
    "link": cmd_link,
    "list": cmd_list,
    "status": cmd_status,
    "unlink": cmd_unlink,
}


COMMAND_HELP = {
    "sync": "fetch remote sources, rebuild, and refresh symlinks",
    "fetch": "clone or update remote sources only",
    "build": "render .build/ only",
    "link": "refresh symlinks only",
    "list": "list every resolvable skill and where it came from",
    "status": "show what is installed, and from which source",
    "unlink": "remove every symlink this repo owns",
}


def global_flags(suppress: bool) -> argparse.ArgumentParser:
    """The flags accepted both before and after the command.

    The copies attached to subcommands default to SUPPRESS so that they do
    not overwrite a value already given ahead of the command — otherwise
    `--json sync` would be silently reset by the subparser's own default.
    """
    parser = argparse.ArgumentParser(add_help=False)
    default = argparse.SUPPRESS if suppress else False
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        default=default,
        help="only print warnings and errors",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        default=default,
        help="print the result as JSON instead of text",
    )
    return parser


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="agents.py",
        description="Manage user-scoped agent skills, agent files, and plugins.",
        epilog=(
            "Every command is safe to re-run, and only ever touches symlinks\n"
            "that point back into this repo. Anything else is left alone."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        parents=[global_flags(suppress=False)],
    )
    # So every command can read it, not just the one that defines the flag.
    parser.set_defaults(no_fetch=False)

    shared = global_flags(suppress=True)
    sub = parser.add_subparsers(dest="command", metavar="command")
    for name, cmd_help in COMMAND_HELP.items():
        p = sub.add_parser(
            name, help=cmd_help, description=cmd_help, parents=[shared]
        )
        if name == "sync":
            p.add_argument(
                "--no-fetch",
                action="store_true",
                help="skip updating remote sources, and do not touch the network",
            )

    args = parser.parse_args()
    Out.quiet = args.quiet
    Out.json = args.json

    # No command: point at sync rather than running it. sync reaches the
    # network and rewrites symlinks, so it should be asked for.
    if not args.command:
        if args.json:
            print(json.dumps({"ok": False, "error": "no command given"}, indent=2))
            sys.exit(1)
        parser.print_help()
        print(
            "\nMost of the time you want:\n"
            "    ./agents.py sync\n"
            "which updates remote sources, rebuilds, and refreshes every symlink."
        )
        return

    result = COMMANDS[args.command](load_config(), args)
    if args.json:
        # Warnings go into the document rather than stderr, so a single
        # parse sees everything that happened.
        print(
            json.dumps(
                {"ok": True, "command": args.command, **result,
                 "warnings": Out.warnings},
                indent=2,
            )
        )


if __name__ == "__main__":
    main()
